### ISSUE TITLE
Implicit constructors are not expanded properly

### ISSUE THREAD

**Issue by vvergu** [metaborg/dynsem#133]
The forgotten feature of implicit constructors is partly broken it seems.

The following spec fragment:

```
module foo

signature
  sorts
    Exp LValue V

  arrows
    read(Int) --> V
    Exp --> V
    LValue -lval-> Int

  constructors
     NumV: Int -> V
     __LValue2Exp__ : LValue -> Exp {implicit}

rules

  lv : LValue --> read(lv).
```

Does not get expanded. The expected expansion of the rule is to:

```
rules
  __LValue2Exp__(lv : LValue) --> v
  where
    lv -lval-> i;
    read(i) --> v.
```

This does not happen because the transformation for expanding implicit reductions cannot find a definition of the `-->` arrow which can be applied to an `LValue`. I.e. it missed the requirement to first wrap `lv : LValue` in the implicit constructor.

**Comment by eelcovisser** [comment]
Note that the issue may be due to 

https://github.com/metaborg/dynsem/issues/132

(unless you could reproduce it without that issue)

**Comment by vvergu** [comment]
Thanks for pointing potential relation to #132 out. Unfortunately that's not the case, it would have been simpler.

This issue is however related to #115.

**Comment by eelcovisser** [comment]
```
Subscript(a, IntV(i)) -lval-> I[i] 
  where 
    read(a) --> ArrayV(I).   
```

should be interpreted as

```
  Subscript(a, __Exp2Index__(IntV(i))) -lval-> I[i] 
  where 
    read(a) --> ArrayV(I).   
```

in tiger / arrays.ds

**Comment by vvergu** [comment]
It appears that the implicit coercion search fails to find paths of this length. In the example there are two implicit conversions that have to be performed. First the implicit constructor has to be matched and then the expression has to be reduced to a value:

```
  Subscript(a, __Exp2Index__(e)) -lval-> I[i] 
  where
    e --> IntV(i);
    read(a) --> ArrayV(I).   
```

For some reason the analysis cannot find that path.
