### ISSUE TITLE
Generating interpreter without dynsem.properties file leads to failure

### ISSUE THREAD

**Issue by eelcovisser** [metaborg/dynsem#141]
Generating an interpreter without a dynsem.properties file in the project leads to failure instead of to a comprehensible error message.

**Comment by vvergu** [comment]
Thanks for opening. b8bfa1f introduces a warning in the editor if a `dynsem.properties` file is missing. The transformation (generate interpreter) now crashes with a comprehensible error message if the file is not present at generation time.
