### ISSUE TITLE
Add `toStrategoTerm` and `toString` for generated term library

### ISSUE THREAD

**Issue by vvergu** [metaborg/dynsem#30]
It is useful to be able to visualize terms (for example as text to see the output of an evaluation). The compiler needs to generate `toStrategoTerm` and `toString` methods for terms. The latter methods should forward to the `toString` methods in the StrategoTerms library.

**Comment by eelcovisser** [comment]
this risks duplicating infrastructure we already have in Spoofax

On Tue, May 17, 2016 at 2:28 PM, Vlad Vergu notifications@github.com
wrote:

> It is useful to be able to visualize terms (for example as text to see the
> output of an evaluation). The compiler needs to generate toString methods
> for terms.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/metaborg/dynsem/issues/30

## 

Professor of Computer Science, TU Delft

http://eelcovisser.org

**Comment by vvergu** [comment]
Spoofax currently has no support for printing DynSem terms to String/ATerms. A way to proceed without duplication is to have the term library know how to convert terms to ATerms and rely on Spoofax functionality to pretty print those if needed. The `toString` methods in the generate term library can forward to the `toString` methods in the StrategoTerms library. I'll edit the issue to make this clear.

**Comment by vvergu** [comment]
Regarding `toString`, @milosonator proposes using reflection:

```
public String toString() {
  String fs = "";
  try{
      for (Field f : getClass().getDeclaredFields()) {
          if (f.getName().startsWith("_")) {
              fs += f.get(this) + ","; 
          }
      }
      if (fs.endsWith(",")) fs = fs.substring(0, fs.length()-1);
  } catch (IllegalAccessException e) {
      System.err.println("error getting field");
  };
  return CONSTRUCTOR + "_" + ARITY + "(" + fs + ")@" + Integer.toHexString(hashCode());
}
```

Thanks @milosonator. This is probably a good intermediate step until i get the `toStrategoTerm` transformation working.

**Comment by Balletie** [comment]
Would letting `ITerm` be an implementor of `IStrategoTerm` be a good idea? They look pretty similar.

**Comment by vvergu** [comment]
Thanks @Balletie. I don't think so. Theoretically it would be a great idea, but the `IStrategoTerm` infrastructure is a mess. I do not want to put a single minute of work into proliferating it :)
