### ISSUE TITLE
Improve handling of variables bound in multiple branches

### ISSUE THREAD

**Issue by vvergu** [metaborg/dynsem#36]
Analysis incorrectly reports duplicate variable errors on variables that are bound in distinct branches of the case pattern match premise.

**Comment by victor-li** [comment]
This would be a nice improvement!

**Comment by eelcovisser** [comment]
please fix

**Comment by vvergu** [comment]
Commit 9a7afe41575ae2c90c5a3f3356a7665530e6c220 disables errors on duplicate variables. It replaces them with errors when a variable is rebound with an incompatible type. This is not really a fix for this issue because it sacrifices sanity of semantics by allowing duplicate variables to silently exist.

The difficulty comes from the way scoping should work in DynSem. A variable which is bound in all case branches of a case match premise must be visible after that premise as well:

```
Constructor() --> Constructor()
where
  case true of {
    true =>
      1 => a;
      1 => b;
    false => 
      2 => a
  };
  a => _;
  b => _.
```

In the above example, the reference to variable `a` after the case premise is OK, but the reference to variable `b` is unresolved (because it is possible at that position that it hasn't been bound yet). The way we solve this in the type analysis is to rename identically in each branch all variables which should be visible after a case match premise. This means that even after renaming both premises `1 => a` and `2 => a` are binding the same name and hence will be recorded as two definitions of the same variable `a` and a duplication error would be shown.

The correct implementation would be to rename each variable in each branch independently and introduce phi nodes after each case-match premise. But that is an enhancement for later.

I'm moving this issue from a bug to an enhancement and rescheduling.
