### ISSUE TITLE
Inspire lifted variables names from sorts

### ISSUE THREAD

**Issue by vvergu** [metaborg/dynsem#39]
Variables introduced for lifted pattern matches are quite uninformative (of the form `lifted_1234`). This could be improved by basing the name on the sort of the introduced variable.

Probably the simplest implementation is to mark lifted variables during lifting and then in a post-pass, once type information is available, to rename them to something that makes sense.

**Comment by casper-bach** [comment]
I guess this is still work in progress? Would be nice to give priority.

The names that are generated based on sorts already (maps) are also pretty verbose. E.g., a `Map(String, Val)`-sorted variable gets the name `l_string_val_n` for some number `n` (almost longer than the sort name itself!).

Related feature request: can we name variables based on their `variables` naming convention when this is specified in DynSem files? E.g.,

```
variables
    r : Env
```

could ensure that all explicated variables of sort `Env` get named `r`?

**Comment by vvergu** [comment]
This is still work not started. It should be doable in reasonable time, but it would have to wait until next week unfortunately. Would that be ok?

I like your proposal about using `variables` to generate nice names, i'm not sure whether this is immediately doable, but i will keep it in mind when i start working on this issue.

**Comment by vvergu** [comment]
One can now call `prettify-vars-module` on an entire module.

**Comment by casper-bach** [comment]
I can call it, but I don't get the same behaviour as when calling DynSem Core.

I can't tell that there's any difference in how I invoke the transformation.

DynSem Core invokes the analysis as follows:

```
module-to-core(|path, project-path) =
    in-project-path(
      ds-to-interp-init-options(|path, project-path)
      ; include-imports
      ; desugar-top
      ; fuse-sections
      ; desugar-varschemes-module
      ; add-extra-typeannos-module
      ; desugar-aliases-module
      ; factorize-module
      ; expand-implicits-module
      ; factorize-module
      ; explicate-module
      ; copy-propagation-module
      ; constant-propagation-module
      ; defactorize-module
      ; insert-wildcards-module
      ; prettify-vars-module
    |project-path)
```

The Coq code generator invokes the analysis as follows:

```
explicate-for-coq(|path, project-path) =
    in-project-path(
      ds-to-interp-init-options(|path, project-path)
      ; include-imports
      ; desugar-top
      ; fuse-sections
      ; desugar-varschemes-module
      ; add-extra-typeannos-module
      ; desugar-aliases-module
      ; factorize-module
      ; expand-implicits-module
      ; factorize-module
      ; explicate-module
      ; copy-propagation-module
      ; constant-propagation-module
      ; defactorize-module
      ; prettify-vars-module
      ; explicate-arrow-types
    |project-path)
```

The only delta here is that Core calls `insert-wildcards-module` whereas Coq does not, and Coq calls `explicate-arrow-types` which Core does not. I can't see how this would result in the observed behaviour (see below).

DynSem Core:

``` rules

  Map(String,V) E_1 |- readVar(x) -default-> E_1[x].

  Map(String,V) E_1 |- bindVar(x, v_1) -default-> {x |--> v_1} + E_1.
```

Coq:

```
Inductive default_bindVar__Arrow : map String V -> bindVar__Arrow -> map String V -> Prop :=
| default_bindVar__Arrow_bindVar0 E_11 x25 v_10:
    default_bindVar__Arrow E_11 (bindVar2 x25 v_10) (map_update E_11 x25 v_10)
.

Inductive default_readVar__Arrow : map String V -> readVar__Arrow -> V -> Prop :=
| default_readVar__Arrow_readVar0 E_10 x24:
    default_readVar__Arrow E_10 (readVar1 x24) (map_lookup E_10 x24)
.
```

The variable `E_1` gets an additional `1` and `0` appended in Coq. Inspecting the DynSem IR, I can see that this happens somewhere in the analysis pipeline (i.e., as part of the `explicate-to-coq` transformation above, before I start Coq pre-processing/code generation). Any ideas where to look would be appreciated.
