### ISSUE TITLE
Generate an interpreter entry-point on ATerms

### ISSUE THREAD

**Issue by vvergu** [metaborg/dynsem#43]
Sometimes it's desirable to evaluate and AST rather than a program which needs to first be parsed. The generated language interpreter entry point should have a method that takes an AST instead of a `Source`.

**Comment by vvergu** [comment]
Also evaluate a text file containing a String representation of an ATerm.

**Comment by vvergu** [comment]
Handy for @milosonator (Grace).

**Comment by vvergu** [comment]
I can see the following usage scenarios for full-program evaluation:
1. full program in concrete syntax (from a Path)
2. full program in concrete syntax (from a String)
3. full program in abstract syntax (from a StrategoTerm)

All of the above should be runnable in both an existent and in a new context. It then becomes interesting to be able to evaluate parts of programs in a new or in an existent context, reading the program into the interpreter in the 3 ways described above.

**Comment by Balletie** [comment]
Since the merge of #55, parsing is separate from the evaluation of a source file. PR #60 adds a static `evaluate` method which can be hooked into through a native Stratego strategy. See the description of #60 for more details.
