### ISSUE TITLE
'Transform resources' has encountered a problem

### ISSUE THREAD

**Issue by aaronang** [metaborg/dynsem#53]
When generating the interpreter for the language project _simpl_, I get the following error message.

> 'Transform resources' has encountered a problem.
> Transformation failed for eclipse:///simpl/trans/simpl.ds

_Note: The triple slashes look odd to me._

The console output can be found here: https://gist.github.com/aaronang/9272577537e857c204f7807e559a8807.

The full path from the _simpl_ language project is: `/home/aaronang/Code/simpl/simpl`, and for the interpreter project: `/home/aaronang/Code/simpl/simpl.interpreter`.

**Comment by milosonator** [comment]
Did you try clean/build? Did you retry it on the latest spoofax? [download on buildfarm](http://buildfarm.metaborg.org/job/spoofax-master/lastSuccessfulBuild/)

**Comment by aaronang** [comment]
@milosonator Just downloaded the newest build and it still does not work unfortunately. Thanks for your reply :smile:

**Comment by aaronang** [comment]
@vvergu Problems also occurs on Windows 10. Here is the console log for Windows 10: https://gist.github.com/aaronang/3244c55149c8d79461c7e53c576e3127.

**Comment by vvergu** [comment]
@aaronang this might point to the issue being in your local setup, with the _dynsem.properties_ file or with the DynSem specification. I'm saying this because @milosonator uses Window 7/10 and generation works.

**Comment by aaronang** [comment]
For now I have resolved the problem. I think the problem is in the [simpl](https://github.com/MetaBorgCube/simpl) project because it does work for our own project.

**Comment by milosonator** [comment]
I've run SIMPL on Windows 10 so I don't think the problem is with the
project per se.
Op 30 mei 2016 9:52 PM schreef "Aaron Ang" notifications@github.com:

**Comment by vvergu** [comment]
I've tried to replicate this issue and i failed. Either it has already been fixed or there is some other issue at play.
