### ISSUE TITLE
isSafeComponentsEnabled() flagged as an error in generated code

### ISSUE THREAD

**Issue by pdmosses** [metaborg/dynsem#76]
The declaration of `isSafeComponentsEnabled()` in a generated interpreter is flagged as an error in Eclipse, indicating that it "must override or implement a supertype".

When running a program using the generated interpreter, Eclipse warns about the error, but allows the run to proceed.

I'm using 2.0.0.20160620-165733-master. I didn't see any errors when using a nightly from about a week ago.

**Comment by vvergu** [comment]
Hi Peter,

This looks like it might be building against an old version of the DynSem interpreter. Can you try Maven update? (Right click on the project and select `Maven > Update Project > Force update snapshot`)

**Comment by pdmosses** [comment]
Thanks for the accurate diagnosis and cure, Vlad! The Maven update fixed the issue.

**Comment by vvergu** [comment]
Happy to hear it is solved now. Thanks for confirmation. Closing the issue.
