### ISSUE TITLE
Nullary meta-functions do not work

### ISSUE THREAD

**Issue by vvergu** [metaborg/dynsem#82]
Nullary meta-functions pass the frontend but crash the generator.

**Comment by vvergu** [comment]
@milosonator: i tried the following:

```
signature
  constructors
    sayhello: --> String

rules
  String(_) --> StringV(sayhello()).

  sayhello() --> "hello".
```

And it works just fine. Can you provide an example where the problem occurs? Thanks.

**Comment by milosonator** [comment]
I also cannot reproduce the error anymore, so maybe this was reported by mistake or it was already fixed. Either way this issue may be closed.
