### ISSUE TITLE
Semantic components in meta-function signatures

### ISSUE THREAD

**Issue by casper-bach** [metaborg/dynsem#92]
As argued in #91, it is useful to explicate based on semantic components in arrow signatures.

It would be nice if we could also specify semantic components in meta-function signatures.

For example, the following meta-function would have a heap and a frame as read-only components:

```
module test
signature
  sorts FrameId H Path
  constructors
    lookup : FrameId, H |- Path --> Addr
```

Update (@vvergu): we'll also put meta-function declarations into their own signature section.

**Comment by casper-bach** [comment]
Note also that meta-functions should be explicated separately, and not based on the default arrow (#86).

**Comment by vvergu** [comment]
@casperbp:

Thank you for the proposal. I'd like to implement this as part of issue #94, but i'm unsure about what is best w.r.t. syntax.

In the example from the OP:

```
module test
signature
  sorts FrameId H Path
  constructors
    lookup : FrameId, H |- Path --> Addr
```

are `FrameId` and `H` the RO components? If so then the following would also be valid:

```
module test
signature
  constructors
    bindVar: E |- String * V --> Env
    write: Int * V :: H --> V :: H
    writebind: E |- String * V :: H --> Env :: H
```

(?) Would it be easier to read if we were to pull the RO components further to the left like so:

```
module test
signature
  constructors
    E |- bindVar: String * V --> Env
    write: Int * V :: H --> V :: H
    E |- writebind: String * V :: H --> Env :: H
```

**Comment by eelcovisser** [comment]
I like the latter proposal since it reflects how rules are written

E |- bindVar(x, v) -> {x |--> v, E}

The downside is that it is harder to identify the name of the meta function; in the IDE that can be addressed by syntax coloring though.

While we're at it, meta-functions should not be declared in the constructors section of the signature.

**Comment by vvergu** [comment]
Putting all meta-functions in their own signature section will probably improve readability so i'll try this:

```
module test
signature
  meta functions
    E |- bindVar: String * V --> Env
    write: Int * V :: H --> V :: H
    E |- writebind: String * V :: H --> Env :: H
```

It's not too hard to change this around later if we dislike the notation. Btw: `meta-functions` or `meta functions`?

**Comment by casper-bach** [comment]
Nice, I agree with having the components how you would write them in rules.

Would it be confusing to have meta-function signatures as `arrows` signature declarations instead?

If we're moving the meta-function signatures out of the constructors section anyway, we could consider bringing it even closer to how rules are written:

```
module test
signature
  arrows
    E |- bindVar(String, V) --> Env
    write(Int, V) :: H --> V :: H
    E |- writebind(String, V) :: H --> Env :: H
```

A possible downside is that this would make the notation used for meta-function signatures somewhat different from the notation used for ordinary constructors and arrows.

But maybe that's fine?

**Comment by eelcovisser** [comment]
well, in a sense this makes it more closely related to arrows: interpreting write(Int, V) as a 'singleton type'. Compare 'regular' arrow declaration to meta function declaration:

```
module test
signature
  arrows
    E |- Expr :: H --> V :: H
    E |- bindVar(String, V) --> Env
    write(Int, V) :: H --> V :: H
    E |- writebind(String, V) :: H --> Env :: H
```

The idea with meta-functions before was to (1) declare a constructor with a unique type, and (2) declare an arrow only for that type. The declarations above achieve that. A question then is whether we should also adopt that notation for constructor declarations

```
signature
   constructors
       Var(String) : Expr
       Fun(String, Expr) : Expr
```

**Comment by vvergu** [comment]
In 90b95cd i implemented the change for meta-functions. Meta-functions are now declared in the `arrows` section using singleton constructor format:

```
module test
signature
  arrows
    E |- Expr :: H --> V :: H
    E |- bindVar(String, V) --> Env
    write(Int, V) :: H --> V :: H
    E |- writebind(String, V) :: H --> Env :: H
```

You can view an example specification using this syntax in the [Simpl project](https://github.com/MetaBorgCube/simpl/blob/dynsem/new-explication/simpl/trans/simpl.ds).

I haven't implemented the change in syntax for the constructors section because it requires changing the generator that's bundled in SDF3 and i don't want to get into that right now. Instead i've opened issue #96.

**Comment by eelcovisser** [comment]
Looks good. And changing constructor declaration syntax is not urgent; it is probably a good idea to have a shared syntax for this across meta-languages.
